### ISSUE TITLE
Missing location of ships ("ligplaatsen") and maybe other objects as well

### ISSUE THREAD

**Issue by bitkat** [berthubert/bagconv#2]
pcodes-geo.zip contains lots of invalid locations (x=-1, y=-1) and it appears that these are (mostly?) ships.
bagserv gives no output at all for such addresses. E.g. 2231BG 293.
(btw the official BAG viewer map also seems to struggle a bit: The location (blue dot) only appears on the map after a search but not after clicking on the object)

**Comment by bitkat** [comment]
Locations of mobile homes ("standplaatsen") are also missing. Example: 2334GJ

**Comment by berthubert** [comment]
This is likely addressed by https://github.com/berthubert/bagconv/commit/260d097f17ba53dde36a8e5265b92aebdb78cdb6 - turns out standplaatsen and ligplaatsen had no 'point' position, only a polygon. We now average the polygon for you.
